class ProfileSetupOptions {
  static const List<String> eastAfricanRegions = [
    'Arusha, Tanzania',
    'Dar es Salaam, Tanzania',
    'Dodoma, Tanzania',
    'Geita, Tanzania',
    'Iringa, Tanzania',
    'Kagera, Tanzania',
    'Katavi, Tanzania',
    'Kigoma, Tanzania',
    'Kilimanjaro, Tanzania',
    'Lindi, Tanzania',
    'Manyara, Tanzania',
    'Mara, Tanzania',
    'Mbeya, Tanzania',
    'Morogoro, Tanzania',
    'Mtwara, Tanzania',
    'Mwanza, Tanzania',
    'Njombe, Tanzania',
    'Pemba North, Tanzania',
    'Pemba South, Tanzania',
    'Pwani, Tanzania',
    'Rukwa, Tanzania',
    'Ruvuma, Tanzania',
    'Shinyanga, Tanzania',
    'Simiyu, Tanzania',
    'Singida, Tanzania',
    'Songwe, Tanzania',
    'Tabora, Tanzania',
    'Tanga, Tanzania',
    'Zanzibar North, Tanzania',
    'Zanzibar South, Tanzania',
    'Zanzibar West, Tanzania',
    'Nairobi, Kenya',
    'Mombasa, Kenya',
    'Kisumu, Kenya',
    'Nakuru, Kenya',
    'Kiambu, Kenya',
    'Uasin Gishu, Kenya',
    'Machakos, Kenya',
    'Nyeri, Kenya',
    'Kakamega, Kenya',
    'Bungoma, Kenya',
    'Kilifi, Kenya',
    'Meru, Kenya',
    'Garissa, Kenya',
    'Kampala, Uganda',
    'Central Region, Uganda',
    'Eastern Region, Uganda',
    'Northern Region, Uganda',
    'Western Region, Uganda',
    'Kigali, Rwanda',
    'Eastern Province, Rwanda',
    'Northern Province, Rwanda',
    'Southern Province, Rwanda',
    'Western Province, Rwanda',
    'Bujumbura, Burundi',
    'Gitega, Burundi',
    'Ngozi, Burundi',
    'Kirundo, Burundi',
    'Muyinga, Burundi',
    'Addis Ababa, Ethiopia',
    'Afar, Ethiopia',
    'Amhara, Ethiopia',
    'Benishangul-Gumuz, Ethiopia',
    'Dire Dawa, Ethiopia',
    'Gambela, Ethiopia',
    'Harari, Ethiopia',
    'Oromia, Ethiopia',
    'Sidama, Ethiopia',
    'Somali Region, Ethiopia',
    'South Ethiopia, Ethiopia',
    'Central Ethiopia, Ethiopia',
    'Tigray, Ethiopia',
    'Djibouti City, Djibouti',
    'Ali Sabieh, Djibouti',
    'Tadjourah, Djibouti',
    'Asmara, Eritrea',
    'Anseba, Eritrea',
    'Debub, Eritrea',
    'Gash-Barka, Eritrea',
    'Northern Red Sea, Eritrea',
    'Southern Red Sea, Eritrea',
    'Banaadir, Somalia',
    'Puntland, Somalia',
    'Somaliland, Somalia',
    'Galmudug, Somalia',
    'Hirshabelle, Somalia',
    'Jubaland, Somalia',
    'South West State, Somalia',
    'Central Equatoria, South Sudan',
    'Eastern Equatoria, South Sudan',
    'Western Equatoria, South Sudan',
    'Jonglei, South Sudan',
    'Lakes, South Sudan',
    'Northern Bahr el Ghazal, South Sudan',
    'Unity, South Sudan',
    'Upper Nile, South Sudan',
    'Warrap, South Sudan',
    'Khartoum, Sudan',
    'Gezira, Sudan',
    'Kassala, Sudan',
    'Red Sea, Sudan',
    'River Nile, Sudan',
    'North Darfur, Sudan',
    'South Darfur, Sudan',
    'Mahe, Seychelles',
    'Praslin, Seychelles',
    'La Digue, Seychelles',
    'Grande Comore, Comoros',
    'Anjouan, Comoros',
    'Moheli, Comoros',
  ];

  static const List<String> educationLevels = [
    'No formal education',
    'Primary school',
    'Lower secondary school',
    'Secondary school',
    'High school',
    'Certificate',
    'Diploma',
    'Advanced diploma',
    'Vocational training',
    'Associate degree',
    'Bachelor\'s degree',
    'Postgraduate diploma',
    'Master\'s degree',
    'Doctorate (PhD)',
    'Professional qualification',
    'Islamic studies certificate',
    'Hafiz / Hifz graduate',
    'Madrasa education',
    'Other',
  ];

  static const List<String> occupations = [
    'Accountant',
    'Administrative Officer',
    'Architect',
    'Auditor',
    'Banker',
    'Business Analyst',
    'Business Owner',
    'Cashier',
    'Chef',
    'Civil Engineer',
    'Cleaner',
    'Construction Manager',
    'Content Creator',
    'Customer Support Specialist',
    'Data Analyst',
    'Dentist',
    'Designer',
    'Digital Marketer',
    'Doctor',
    'Driver',
    'Economist',
    'Electrical Engineer',
    'Entrepreneur',
    'Event Planner',
    'Farmer',
    'Finance Officer',
    'Flight Attendant',
    'Graphic Designer',
    'HR Manager',
    'Hotel Manager',
    'Journalist',
    'Lawyer',
    'Lecturer',
    'Machine Operator',
    'Marketing Manager',
    'Mechanic',
    'Medical Laboratory Scientist',
    'Nurse',
    'Pharmacist',
    'Photographer',
    'Pilot',
    'Police Officer',
    'Procurement Officer',
    'Product Manager',
    'Project Manager',
    'Real Estate Agent',
    'Receptionist',
    'Researcher',
    'Sales Executive',
    'Security Officer',
    'Shopkeeper',
    'Social Worker',
    'Software Developer',
    'Store Manager',
    'Supply Chain Officer',
    'Tailor',
    'Teacher',
    'Technician',
    'Translator',
    'Travel Consultant',
    'UI/UX Designer',
    'University Student',
    'Veterinarian',
    'Video Editor',
    'Waiter / Waitress',
    'Web Developer',
    'Writer',
    'Other',
  ];

  static const List<String> languages = [
    'Afrikaans',
    'Akan',
    'Albanian',
    'Amharic',
    'Arabic',
    'Armenian',
    'Assamese',
    'Azerbaijani',
    'Basque',
    'Belarusian',
    'Bengali',
    'Bosnian',
    'Bulgarian',
    'Burmese',
    'Catalan',
    'Cebuano',
    'Chichewa',
    'Chinese (Cantonese)',
    'Chinese (Mandarin)',
    'Croatian',
    'Czech',
    'Danish',
    'Dari',
    'Dutch',
    'English',
    'Estonian',
    'Ewe',
    'Filipino',
    'Finnish',
    'French',
    'Fulani',
    'Galician',
    'Georgian',
    'German',
    'Greek',
    'Gujarati',
    'Haitian Creole',
    'Hausa',
    'Hebrew',
    'Hindi',
    'Hungarian',
    'Icelandic',
    'Igbo',
    'Indonesian',
    'Irish',
    'Italian',
    'Japanese',
    'Javanese',
    'Kannada',
    'Kazakh',
    'Khmer',
    'Kinyarwanda',
    'Konkani',
    'Korean',
    'Kurdish',
    'Kyrgyz',
    'Lao',
    'Latvian',
    'Lingala',
    'Lithuanian',
    'Luganda',
    'Luo',
    'Luxembourgish',
    'Macedonian',
    'Malagasy',
    'Malay',
    'Malayalam',
    'Maltese',
    'Maori',
    'Marathi',
    'Mongolian',
    'Nepali',
    'Norwegian',
    'Odia',
    'Oromo',
    'Pashto',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Quechua',
    'Romanian',
    'Russian',
    'Samoan',
    'Serbian',
    'Shona',
    'Sindhi',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Somali',
    'Spanish',
    'Sundanese',
    'Swahili',
    'Swedish',
    'Tajik',
    'Tamil',
    'Tatar',
    'Telugu',
    'Thai',
    'Tigrinya',
    'Tswana',
    'Turkish',
    'Turkmen',
    'Ukrainian',
    'Urdu',
    'Uyghur',
    'Uzbek',
    'Vietnamese',
    'Welsh',
    'Wolof',
    'Xhosa',
    'Yoruba',
    'Zulu',
  ];
}
